# Generated by Django 3.0.2 on 2020-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Student_Registerd_Cources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Roll_No', models.CharField(max_length=50)),
                ('Student_Registerd_Subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Registerd_No', models.CharField(max_length=50)),
                ('Student_Name', models.CharField(max_length=50)),
                ('Student_Roll_NO', models.CharField(max_length=50)),
                ('Student_Mobile_No', models.CharField(max_length=50)),
            ],
        ),
    ]
