# Generated by Django 3.0.2 on 2020-04-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0002_add_student_registerd_cources_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Subjects_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.subjects'),
        ),
    ]
