# Generated by Django 3.0.2 on 2020-04-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0003_auto_20200425_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='principle.subjects'),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Subjects_Code',
            field=models.CharField(max_length=50),
        ),
    ]
