# Generated by Django 3.0.2 on 2020-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0004_auto_20200426_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addteacher',
            name='Teacher_Subjects',
        ),
        migrations.AddField(
            model_name='addteacher',
            name='Teacher_Subjects',
            field=models.ManyToManyField(to='principle.subjects'),
        ),
    ]
