# Generated by Django 3.0.2 on 2020-04-27 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0005_auto_20200427_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Name',
            field=models.CharField(default='sd', max_length=50),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Password',
            field=models.CharField(default='sd', max_length=50),
        ),
        migrations.RemoveField(
            model_name='addteacher',
            name='Teacher_Subjects',
        ),
        migrations.AddField(
            model_name='addteacher',
            name='Teacher_Subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principle.subjects'),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Subjects_Code',
            field=models.CharField(default='sd', max_length=50),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='Teacher_Username',
            field=models.CharField(default='sd', max_length=50),
        ),
    ]
